package com.banking.account.bankAccount.model;

import com.banking.account.accountStatement.model.AccountStatement;
import com.banking.account.balance.model.Balance;
import com.banking.account.exception.InvalidAccountStateException;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Root aggregate of the Account bounded context.
 *
 * <p>Represents a bank account owned by a single user. This entity deliberately
 * holds only the account's structural data (IBAN, type, status, timestamps).
 * The mutable financial state (available/blocked balance) lives in the separate
 * {@link Balance} entity so that Hibernate Envers can capture balance changes
 * with their own revision history independently from structural account changes.</p>
 *
 * <p>{@link Audited @Audited} causes Hibernate Envers to create a shadow table
 * {@code bank_accounts_aud} that records every INSERT/UPDATE/DELETE with a
 * revision number, timestamp, and the custom fields from
 * {@link com.banking.account.audit.CustomRevisionEntity}
 * (modifiedBy, clientIp).</p>
 */
@Entity
@Audited
@Table(
    name = "bank_accounts",
    indexes = {
        @Index(name = "idx_ba_user_id",  columnList = "user_id"),
        @Index(name = "idx_ba_iban",     columnList = "iban"),
        @Index(name = "idx_ba_status",   columnList = "status"),
        @Index(name = "idx_ba_user_status", columnList = "user_id, status")
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@ToString(exclude = {"balance", "statements"})
public class BankAccount {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false, columnDefinition = "BINARY(16)")
    @EqualsAndHashCode.Include
    private UUID id;

    /**
     * Reference to the owner in User-Service. We store only the UUID —
     * no FK to a users table (cross-service DB coupling is forbidden).
     */
    @Column(name = "user_id", nullable = false, updatable = false, columnDefinition = "BINARY(16)")
    private UUID userId;

    /**
     * International Bank Account Number (IBAN) — generated by this service
     * using a country-specific algorithm. Unique across the platform.
     * Format: BG80BNBG96611020345678 (22 chars for Bulgaria).
     */
    @Column(name = "iban", nullable = false, unique = true, length = 34)
    private String iban;

    /**
     * Internal account number used for display and legacy compatibility.
     */
    @Column(name = "account_number", nullable = false, unique = true, length = 20)
    private String accountNumber;

    @Enumerated(EnumType.STRING)
    @Column(name = "account_type", nullable = false, length = 20)
    private AccountType accountType;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    @Builder.Default
    private AccountStatus status = AccountStatus.ACTIVE;

    /**
     * The live balance of this account.
     * CASCADE.ALL — balance is created, updated, and deleted with the account.
     * FETCH.EAGER — balance is always loaded with the account (needed for every operation).
     */
    @OneToOne(
        mappedBy = "bankAccount",
        cascade = CascadeType.ALL,
        fetch = FetchType.EAGER,
        orphanRemoval = true
    )
    private Balance balance;

    /**
     * Generated statements — loaded lazily; only fetched when explicitly requested.
     * Marked @NotAudited because statements are append-only records and don't need
     * their own revision entries within the BankAccount audit table.
     */
    @OneToMany(
        mappedBy = "bankAccount",
        cascade = CascadeType.ALL,
        fetch = FetchType.LAZY,
        orphanRemoval = true
    )
    @Builder.Default
    @NotAudited
    private List<AccountStatement> statements = new ArrayList<>();

    @Column(name = "opened_at", nullable = false, updatable = false)
    private LocalDateTime openedAt;

    @Column(name = "closed_at")
    private LocalDateTime closedAt;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;



    // ─── Bidirectional relation helpers ─────────────────────────────────

    /**
     * Sets the balance and wires the back-reference so both sides of the
     * @OneToOne relationship are always consistent.
     */
    public void assignBalance(Balance balance) {
        this.balance = balance;
        balance.setBankAccount(this);
    }

    // ─── Domain state transitions ────────────────────────────────────────

    /**
     * Freezes the account. Only allowed when {@link AccountStatus#ACTIVE}.
     * After freezing, debits and outgoing transfers are blocked; credits still allowed.
     *
     * @throws InvalidAccountStateException if the account is not ACTIVE
     */
    public void freeze() {
        if (this.status != AccountStatus.ACTIVE) {
            throw new InvalidAccountStateException(
                    "Account must be ACTIVE to be frozen. Current status: " + this.status);
        }
        this.status = AccountStatus.FROZEN;
    }

    /**
     * Restores a frozen account to active.
     *
     * @throws InvalidAccountStateException if the account is not FROZEN
     */
    public void unfreeze() {
        if (this.status != AccountStatus.FROZEN) {
            throw new InvalidAccountStateException(
                    "Account must be FROZEN to be unfrozen. Current status: " + this.status);
        }
        this.status = AccountStatus.ACTIVE;
    }

    /**
     * Permanently closes the account.
     * Pre-conditions: account must have a zero available AND zero blocked balance.
     *
     * @throws InvalidAccountStateException if already CLOSED or balance is non-zero
     */
    public void close() {
        if (this.status == AccountStatus.CLOSED) {
            throw new InvalidAccountStateException("Account is already CLOSED.");
        }
        if (balance != null && (!balance.getAvailableMoney().isZero() || !balance.getBlockedMoney().isZero())) {
            throw new InvalidAccountStateException(
                    "Cannot close account with non-zero balance. Available: %s, Blocked: %s"
                            .formatted(balance.getAvailableMoney(), balance.getBlockedMoney()));
        }
        this.status = AccountStatus.CLOSED;
        this.closedAt = LocalDateTime.now();
    }

    // ─── Guard helpers ───────────────────────────────────────────────────

    /** Returns true if the account can initiate outgoing transfers and debits. */
    public boolean canDebit() {
        return this.status == AccountStatus.ACTIVE;
    }

    /** Returns true if the account can receive incoming credits. */
    public boolean canCredit() {
        return this.status == AccountStatus.ACTIVE || this.status == AccountStatus.FROZEN;
    }

    /** Returns true if the account still has an open status (not CLOSED). */
    public boolean isOpen() {
        return this.status != AccountStatus.CLOSED;
    }
}
